### ISSUE TITLE
Set-WMINameSpaceSecurity: Permissions added do not apply to subnamespaces

### ISSUE THREAD

**Issue by alexsrb** [grbray/PowerShell#4]
Dear Graeme,

We would very much appreciate your feedback concerning the below - this script is so close to solving a really big problem for us (and I believe for many more, after going through multiple google search/result pages...).

Context:
- We are trying to assign specific permissions on the default Windows WMI namespace (root\cimv2) for various domain groups/accounts on many machines. We could e.g. have this script run as startup script as part of a GPO.
- The various (monitoring) tools that use these groups/accounts leverage information found in subnamespaces of the default namespace.
- Windows Server 2019 environment.

The script only seems to assign permissions on the target namespace itself:
- before running the script (default permissions):
![image](https://user-images.githubusercontent.com/4201994/177532907-0eecc072-f908-4d7f-a2f1-fedb064ac077.png)
- after running the script (test using the domain admin account to add Enable rights for a "test@[...]" domain user account):
![image](https://user-images.githubusercontent.com/4201994/177533348-d9ef2682-c0bc-45ef-b0b6-8f61fc04f817.png)

How can this script be used for granting permissions to the target namespace AND TO ITS children ("This namespace and subnamespaces")?
We have tried to use the "allowInherit" option, without success unfortunately:
![image](https://user-images.githubusercontent.com/4201994/177535103-d7d8688f-608b-415c-8db4-733c35625404.png)

Thank you,
Alexandru

**Comment by grbray** [comment]
Fixed via changing line 151.  Also adjusted Remote computer and made parameters to leverage ValidateSet
